name: k8s-cluster-stig-baseline
title: Kubernetes 1.16 Based upon Kubernetes 1.16 Security Technical Implementation Guideline (STIG) 
maintainer: MITRE SAF Team
copyright: MITRE, 2022
copyright_email: saf@groups.mitre.org
license: Apache-2.0
summary: InSpec testing for baseline compliance with the Kubernetes STIG
description: An InSpec profile verifying compliance with Kubernetes STIG version 1.16 
version: 1.0.1
inspec_version: ">= 4.0"
supports:
- platform: k8s

depends:
- name: inspec-k8s
  path: ../inspec-k8s

inputs:
  - name: k8s_minium_version
    description: 'Minimum version of Kubernetes deployment'
    type: string
    value: 'v1.19.5'
    required: true

  - name: k8s_default_namespaces
    description: Default namespaces used by kubernetes itself, which should not contain any user-defined resources
    type: Array
    required: true
    value:
      - 'default'
      - 'kube-public'
      - 'kube-node-lease'
  

  - name: k8s_approved_services
    description: Services that are necessary to run inside the default kubernetes namespaces
    type: Array
    required: true
    value:
      - 'kubernetes'
